#!/usr/bin/env python
"""Run RRT-MIL survival models on MIRMIL train/val/test splits.

This is an adapter around the external RRT-MIL Survival models. It keeps the
reference model/loss definitions intact, but uses the Split column generated by
tools/prepare_rrtmil_survival_csv.py instead of RRT-MIL's internal 5-fold split.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import random
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sksurv.metrics import concordance_index_censored
from torch.utils.data import DataLoader, Dataset


RRT_ROOT = Path("/data15/data15_5/fanhao/projects/reference/RRT-MIL/Survival")
if str(RRT_ROOT) not in sys.path:
    sys.path.insert(0, str(RRT_ROOT))

from utils.loss import NLLSurvLoss  # noqa: E402


class SplitSurvivalDataset(Dataset):
    def __init__(
        self,
        csv_path: Path,
        split: str,
        cut_bins: np.ndarray | None = None,
        num_bins: int = 4,
        max_instances: int = 0,
        sampling: str = "random",
        seed: int = 1,
        cache_dir: Path | None = None,
    ):
        self.csv_path = Path(csv_path)
        self.split = split
        self.num_bins = int(num_bins)
        self.max_instances = int(max_instances or 0)
        self.sampling = str(sampling)
        self.seed = int(seed)
        self.cache_dir = Path(cache_dir) if cache_dir else None
        rows = pd.read_csv(self.csv_path)
        if "Split" not in rows.columns:
            raise KeyError(f"{self.csv_path} must contain a Split column")
        rows = rows[rows["Split"].astype(str) == split].copy().reset_index(drop=True)
        if rows.empty:
            raise ValueError(f"No rows for split={split} in {self.csv_path}")
        rows["Status"] = pd.to_numeric(rows["Status"], errors="raise").astype(int)
        rows["Event"] = pd.to_numeric(rows["Event"], errors="raise")
        self.cut_bins = self._fit_bins(rows) if cut_bins is None else np.asarray(cut_bins, dtype=float)
        rows["Label"] = self._apply_bins(rows, self.cut_bins)
        self.rows = rows

    def _fit_bins(self, rows: pd.DataFrame) -> np.ndarray:
        eps = 1e-6
        uncensored = rows[rows["Status"] == 1]
        if len(uncensored) < self.num_bins:
            raise ValueError(
                f"Not enough uncensored samples in split={self.split}: "
                f"{len(uncensored)} < {self.num_bins}"
            )
        _, q_bins = pd.qcut(
            uncensored["Event"],
            q=self.num_bins,
            retbins=True,
            labels=False,
            duplicates="drop",
        )
        if len(q_bins) != self.num_bins + 1:
            raise ValueError(f"qcut produced {len(q_bins) - 1} bins, expected {self.num_bins}")
        q_bins[-1] = rows["Event"].max() + eps
        q_bins[0] = rows["Event"].min() - eps
        return q_bins

    @staticmethod
    def _apply_bins(rows: pd.DataFrame, cut_bins: np.ndarray) -> np.ndarray:
        cut_bins = np.asarray(cut_bins, dtype=float).copy()
        cut_bins[0] = -np.inf
        cut_bins[-1] = np.inf
        labels = pd.cut(
            rows["Event"],
            bins=cut_bins,
            labels=False,
            right=False,
            include_lowest=True,
        )
        labels = labels.astype(int).to_numpy()
        labels[labels < 0] = -1
        return labels

    def __len__(self) -> int:
        return len(self.rows)

    def _sample_instances(self, features: torch.Tensor, index: int) -> torch.Tensor:
        if self.max_instances <= 0 or features.shape[0] <= self.max_instances:
            return features
        n = features.shape[0]
        if self.sampling == "uniform":
            idx = torch.linspace(0, n - 1, self.max_instances).long()
            return features[idx]
        if self.sampling == "head":
            return features[: self.max_instances]
        rng = np.random.default_rng(self.seed + index)
        idx = rng.choice(n, size=self.max_instances, replace=False)
        idx.sort()
        return features[torch.from_numpy(idx).long()]

    @staticmethod
    def _torch_load(path: str | Path) -> torch.Tensor:
        try:
            return torch.load(path, map_location="cpu", weights_only=True)
        except TypeError:
            return torch.load(path, map_location="cpu")

    def _cache_path(self, index: int, row: pd.Series) -> Path | None:
        if self.cache_dir is None or self.max_instances <= 0:
            return None
        key = "|".join(
            [
                str(self.csv_path.resolve()),
                self.split,
                str(index),
                str(row["ID"]),
                str(row["WSI"]),
                self.sampling,
                str(self.seed),
                str(self.max_instances),
            ]
        )
        digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
        return self.cache_dir / self.csv_path.stem / self.split / f"{digest}.pt"

    def __getitem__(self, index: int):
        row = self.rows.iloc[index]
        cache_path = self._cache_path(index, row)
        if cache_path is not None and cache_path.exists():
            features = self._torch_load(cache_path).float()
        else:
            tensors = [self._torch_load(p) for p in str(row["WSI"]).split(";")]
            features = torch.cat(tensors, dim=0).float()
            features = self._sample_instances(features, index)
            if cache_path is not None:
                cache_path.parent.mkdir(parents=True, exist_ok=True)
                tmp_path = cache_path.with_suffix(f".{os.getpid()}.tmp")
                torch.save(features, tmp_path)
                os.replace(tmp_path, cache_path)
        censorship = 1 if int(row["Status"]) == 0 else 0
        return (
            str(row["ID"]),
            features,
            float(row["Event"]),
            int(censorship),
            int(row["Label"]),
        )


def collate_single(batch):
    if len(batch) != 1:
        raise ValueError("This runner expects batch_size=1")
    case_id, features, event, censorship, label = batch[0]
    return (
        [case_id],
        features.unsqueeze(0),
        torch.tensor([event], dtype=torch.float32),
        torch.tensor([censorship], dtype=torch.float32),
        torch.tensor([label], dtype=torch.long),
    )


def build_model(model_name: str, n_features: int, num_classes: int, epeg_k: int, crmsa_k: int):
    if model_name == "MeanMIL":
        from models.Mean_Max.network import MeanMIL

        return MeanMIL(n_classes=num_classes, dropout=True, act="relu", n_features=n_features)
    if model_name == "MaxMIL":
        from models.Mean_Max.network import MaxMIL

        return MaxMIL(n_classes=num_classes, dropout=True, act="relu", n_features=n_features)
    if model_name == "AttMIL":
        from models.AttMIL.network import DAttention

        return DAttention(n_classes=num_classes, dropout=0.25, act="relu", n_features=n_features)
    if model_name == "TransMIL":
        from models.TransMIL.network import TransMIL

        return TransMIL(n_classes=num_classes, dropout=0.25, act="relu", n_features=n_features)
    if model_name == "RRTMIL":
        from models.RRTMIL.network import RRT

        return RRT(
            n_classes=num_classes,
            epeg_k=epeg_k,
            crmsa_k=crmsa_k,
            input_dim=n_features,
            region_num=16,
        )
    raise NotImplementedError(model_name)


def cindex_from_arrays(events: list[float], censorships: list[float], risks: list[float]) -> float:
    return float(
        concordance_index_censored(
            (1 - np.asarray(censorships)).astype(bool),
            np.asarray(events),
            np.asarray(risks),
            tied_tol=1e-8,
        )[0]
    )


def run_epoch(model, loader, criterion, device, optimizer=None):
    train = optimizer is not None
    model.train(train)
    total_loss = 0.0
    events: list[float] = []
    censorships: list[float] = []
    risks: list[float] = []
    for _, features, event, censorship, label in loader:
        features = features.to(device)
        event = event.to(device)
        censorship = censorship.to(device)
        label = label.to(device)
        if train:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(train):
            hazards, survival = model(features)
            loss = criterion(hazards=hazards, S=survival, Y=label, c=censorship)
            if train:
                loss.backward()
                optimizer.step()
        total_loss += float(loss.detach().cpu())
        risk = -torch.sum(survival, dim=1).detach().cpu().numpy()
        risks.extend(risk.tolist())
        events.extend(event.detach().cpu().numpy().tolist())
        censorships.extend(censorship.detach().cpu().numpy().tolist())
    return {
        "loss": total_loss / max(len(loader), 1),
        "c_index": cindex_from_arrays(events, censorships, risks),
    }


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", required=True, type=Path)
    parser.add_argument("--model", required=True, choices=["MeanMIL", "MaxMIL", "AttMIL", "TransMIL", "RRTMIL"])
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--max-instances", type=int, default=4096)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--num-bins", type=int, default=4)
    parser.add_argument("--n-features", type=int, default=1024)
    parser.add_argument("--epeg-k", type=int, default=15)
    parser.add_argument("--crmsa-k", type=int, default=3)
    parser.add_argument("--cache-dir", type=Path, default=None)
    args = parser.parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)

    train_ds = SplitSurvivalDataset(
        args.csv,
        "train",
        num_bins=args.num_bins,
        max_instances=args.max_instances,
        sampling="random",
        seed=args.seed,
        cache_dir=args.cache_dir,
    )
    val_ds = SplitSurvivalDataset(
        args.csv,
        "val",
        cut_bins=train_ds.cut_bins,
        num_bins=args.num_bins,
        max_instances=args.max_instances,
        sampling="uniform",
        seed=args.seed,
        cache_dir=args.cache_dir,
    )
    test_ds = SplitSurvivalDataset(
        args.csv,
        "test",
        cut_bins=train_ds.cut_bins,
        num_bins=args.num_bins,
        max_instances=args.max_instances,
        sampling="uniform",
        seed=args.seed,
        cache_dir=args.cache_dir,
    )
    loaders = {
        "train": DataLoader(train_ds, batch_size=1, shuffle=True, num_workers=args.num_workers, collate_fn=collate_single),
        "val": DataLoader(val_ds, batch_size=1, shuffle=False, num_workers=args.num_workers, collate_fn=collate_single),
        "test": DataLoader(test_ds, batch_size=1, shuffle=False, num_workers=args.num_workers, collate_fn=collate_single),
    }
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    model = build_model(args.model, args.n_features, args.num_bins, args.epeg_k, args.crmsa_k).to(device)
    criterion = NLLSurvLoss(alpha=0.0)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    dataset_name = args.csv.name.replace("_rrtmil.csv", "")
    out_dir = args.output_dir / dataset_name / args.model / f"seed{args.seed}_max{args.max_instances}_{time.strftime('%Y%m%d_%H%M%S')}"
    out_dir.mkdir(parents=True, exist_ok=True)
    meta = {
        "csv": str(args.csv),
        "csv_sha256": sha256_file(args.csv),
        "model": args.model,
        "epochs": args.epochs,
        "seed": args.seed,
        "max_instances": args.max_instances,
        "num_bins": args.num_bins,
        "lr": args.lr,
        "weight_decay": args.weight_decay,
        "cache_dir": str(args.cache_dir) if args.cache_dir else None,
        "train_cases": len(train_ds),
        "val_cases": len(val_ds),
        "test_cases": len(test_ds),
        "cut_bins": train_ds.cut_bins.tolist(),
    }
    (out_dir / "metadata.json").write_text(json.dumps(meta, indent=2))

    rows = []
    best_val = -np.inf
    best_epoch = -1
    best_test = None
    best_state_path = out_dir / "best_model.pth"
    for epoch in range(args.epochs):
        train_metrics = run_epoch(model, loaders["train"], criterion, device, optimizer)
        val_metrics = run_epoch(model, loaders["val"], criterion, device)
        test_metrics = run_epoch(model, loaders["test"], criterion, device)
        row = {
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_c_index": train_metrics["c_index"],
            "val_loss": val_metrics["loss"],
            "val_c_index": val_metrics["c_index"],
            "test_loss": test_metrics["loss"],
            "test_c_index": test_metrics["c_index"],
        }
        rows.append(row)
        print(
            f"epoch={epoch} train={train_metrics['c_index']:.4f} "
            f"val={val_metrics['c_index']:.4f} test={test_metrics['c_index']:.4f}",
            flush=True,
        )
        if val_metrics["c_index"] > best_val:
            best_val = val_metrics["c_index"]
            best_epoch = epoch
            best_test = test_metrics["c_index"]
            torch.save(model.state_dict(), best_state_path)

    with (out_dir / "epoch_log.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    summary = {
        **meta,
        "best_epoch": best_epoch,
        "best_val_c_index": best_val,
        "test_c_index_at_best_val": best_test,
        "result_dir": str(out_dir),
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
